#---------------------------------------------------------------------------------------
# 1. docker-compose -p microservices-comp3095-ecommerce -f docker-compose.yml up -d
#       --- this command will start the containers in detached mode without rebuilding (if they already exist)
#
# 2. docker-compose - p microservices-comp3095-ecommerce -f docker-compose.yml up -d --build
#       --- this command forces the rebuild of images, even if the images already exists, before starting the containers
#
# --------------------------------------------------------------------------------------------------
version: '3.9'

services:

  inventory-service:
    image: 8160202/inventory-service
    ports:
      - "8003:8083"
    build:
      context: ./inventory-service     # The directory where the Dockerfile resides
      dockerfile: ./Dockerfile       # Specify the Dockerfile for use to build image
    container_name: inventory-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5434/inventory-service
      - SPRING_DATASOURCE_USERNAME:admin
      - SPRING_DATASOURCE_PASSWORD:password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres-inventory
    networks:
      - spring


  order-service:
    image: order-service
    ports:
      - "8084:8084"
    build:
      context: ./order-service     # The directory where the Dockerfile resides
      dockerfile: ./Dockerfile       # Specify the Dockerfile for use to build image
    container_name: order-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mongodb
    networks:
      - spring


  product-service:
    image: product-service
    ports:
      - "8084:8084"
    build:
      context: ./product-service     # The directory where the Dockerfile resides
      dockerfile: ./Dockerfile       # Specify the Dockerfile for use to build image
    container_name: product-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mongodb
    networks:
      - spring

  mongodb:
    image: mongo:latest
    ports:
      - "21017:21017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./data/mongo/products:/data/db
      - ./init/mongo/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js #:ro
    container_name: mongodb
    # restart: unless-stopped
    # command: mongod --auth
    networks:
      - spring


  mongo-express:
    image: mongo-express
    ports:
      - "8082:8082"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    container_name: comp3095-mongo-express
    depends_on:
      - mongodb
    networks:
      - spring

#optional
volumes:
  mongo-db:
    driver: local

networks:
  spring:
    driver: bridge